apiVersion: infra.sharduljunagade.github.io/v1alpha1
kind: DNSMonitor
metadata:
  name: dns-monitor
  namespace: default
spec:
  namespace: kube-system
  probeIntervalSeconds: 30
  testDomain: "kubernetes.default.svc.cluster.local"
  failureThreshold: 3
  desiredReplicas: 1
