apiVersion: infra.sharduljunagade.github.io/v1alpha1
kind: DNSMonitor
metadata:
  labels:
    app.kubernetes.io/name: coredns-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsmonitor-sample
spec:
  # TODO(user): Add fields here
