---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: dnsmonitors.infra.sharduljunagade.github.io
spec:
  group: infra.sharduljunagade.github.io
  names:
    kind: DNSMonitor
    listKind: DNSMonitorList
    plural: dnsmonitors
    singular: dnsmonitor
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DNSMonitor is the Schema for the dnsmonitors API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of DNSMonitor
            properties:
              desiredReplicas:
                description: DesiredReplicas - minimum number of CoreDNS replicas
                  to enforce (optional)
                format: int32
                type: integer
              failureThreshold:
                description: FailureThreshold - number of consecutive probe failures
                  before restart
                type: integer
              namespace:
                description: 'Namespace where CoreDNS runs (default: kube-system)'
                type: string
              probeIntervalSeconds:
                description: Probe interval in seconds
                type: integer
              testDomain:
                description: 'DNS domain to resolve for health check (default: kubernetes.default.svc.cluster.local)'
                type: string
            type: object
          status:
            description: status defines the observed state of DNSMonitor
            properties:
              failCount:
                type: integer
              healthy:
                type: boolean
              lastAction:
                type: string
              lastChecked:
                format: date-time
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
