# This rule is not used by the project coredns-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the infra.sharduljunagade.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: coredns-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsmonitor-editor-role
rules:
- apiGroups:
  - infra.sharduljunagade.github.io
  resources:
  - dnsmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.sharduljunagade.github.io
  resources:
  - dnsmonitors/status
  verbs:
  - get
